### PR TITLE
Introduce TestData#delete to simplify testing of flag deletion.

### PR DESCRIPTION
**Pull request by dmvk**
**Requirements**

- [x] I have added test coverage for new or changed functionality
- [x] I have followed the repository's [pull request submission guidelines](../blob/master/CONTRIBUTING.md#submitting-pull-requests)
- [x] I have validated my changes against all supported platform versions

**Related issues**

Provide links to any issues in this repository or elsewhere relating to this pull request.

**Describe the solution you've provided**

Provide a clear and concise description of what you expect to happen.

**Describe alternatives you've considered**

Provide a clear and concise description of any alternative solutions or features you've considered.

**Additional context**

I'm writing a custom dataStore that allows falling back to k8s configmap and I don't have a simple way to test tombstones.

### CODE REVIEW

**Review by tanderson-ld — APPROVED** [review]

**Comment by tanderson-ld** [comment]
Hi @dmvk , thank you for the contribution.  We are working to migrate this repository to our java-core repo and so this may get released mid next week if that repo migration goes to plan.  Does that sound satisfactory?

**Comment by tanderson-ld** [comment]
Planning to merge around the same time as the java-server-sdk is migrated to use this added functionality as a CI/CD build system update test.

**Comment by dmvk** [comment]
@tanderson-ld Thanks, that sounds great, I haven't expected things to go this fast <3 Looking forward for the release!

**Comment by tanderson-ld** [comment]
Migrated your changes to the new repo.  Once those are merged we'll release this change: https://github.com/launchdarkly/java-core/pull/21

**Comment by tanderson-ld** [comment]
java-core PR has merged https://github.com/launchdarkly/java-core/pull/21

**Comment by tanderson-ld** [comment]
The code changes are now released in java-server-sdk 7.5.0.  Let us know if it works!  This is a good verification of our reshuffling of our release pipeline.

**Pull request closed without merging**
